In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [57]:
# 1
# Create a NumPy array of size 4x3 and filled with random numbers from 10 to
# 98 (inclusive). Calculate the sum of all elements, 
# the sum of each row and
# each column.

arr = np.random.randint(10, 98 + 1, (4, 3))
display(arr)
display('sum', arr.sum())
display('sum row', arr.sum(axis=1))
display('sum col', arr.sum(axis=0))

array([[46, 45, 59],
       [85, 59, 76],
       [66, 19, 22],
       [13, 23, 73]])

'sum'

586

'sum row'

array([150, 220, 107, 109])

'sum col'

array([210, 146, 230])

In [64]:
# 2
# Create a NumPy array of size 10 filled with random numbers from 0 to 10.
# Count how many of them are even numbers.
arr = np.random.randint(0, 10 + 1, (1, 10))
display(arr)
display(arr[arr % 2 == 0])
display(len(arr[arr % 2 == 0]))
display(arr[arr % 2 == 0].size)

array([[6, 6, 2, 0, 6, 5, 9, 5, 2, 4]])

array([6, 6, 2, 0, 6, 2, 4])

7

7

In [73]:
# 3
# Create a NumPy array of size 100, filled with a sequence of numbers from 0
# to 99.
# 2. Reshape this array into 10 rows and 10 columns.
# 3. Replace all values in the array which are greater than 50 with -1.
# 4. Calculate the sum of all elements in the array.
# 5. Calculate the mean of all elements in the array

arr = np.arange(0, 99 + 1)
arr.reshape(10, 10)
arr[arr > 50] = -1
display(arr)
display(arr.sum())
display(arr.mean())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

1226

12.26

In [78]:
# 4
# 1. Create an array of 10 elements with numbers between 0 -100 with the same
# space between each element.
# 2. Generate a new array that has all values from the previous array that are
# greater than 50 or lower than 20.
# 3. Reshape the array to a matrix array possible, (for example if its possible to
# reshape the array to 4X3 matrix generate it)

arr = np.linspace(0, 100, 10)
display(arr)
arr = arr[(arr > 50) | (arr < 20)]
display(arr)
display(arr.reshape(7, 1))

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

array([  0.        ,  11.11111111,  55.55555556,  66.66666667,
        77.77777778,  88.88888889, 100.        ])

array([[  0.        ],
       [ 11.11111111],
       [ 55.55555556],
       [ 66.66666667],
       [ 77.77777778],
       [ 88.88888889],
       [100.        ]])